### ISSUE TITLE
update to datagrip 2020.1.4 error

### ISSUE THREAD

**Issue by UlionTse** [pengzhile/ide-eval-resetter#5]
License Server response has not passed data integrity check: Certificate used to sign the license is not signed by JetBrains root certificate (1)

**Comment by pengzhile** [comment]
看清楚，这是试用时间重置项目。

**Comment by UlionTse** [comment]
@pengzhile 嗯，也没找到其他相关项目，所以可能这个项目相关性高，所以就提了。我在你微信公众号也发你了，不过是机器人，不确定你是否会看。加群了，还没通过，所以就在这反馈了。
